### PR TITLE
Initial hyperlink support

### PR DESCRIPTION
**Pull request by SolitudeSF**
inital implementation of #1

### CODE REVIEW

**Comment by SolitudeSF** [comment]
added a `hyperlink` flag.

**Comment by SolitudeSF** [comment]
now i'm just not sure how reliable is my path extraction, since im not familiar with internals/nuance of lc.

**Comment by SolitudeSF** [comment]
and why fmt closure requires `var Fil`?

**Comment by c-blake** [comment]
I feel like there was some reason for `var Fil`, like some lone formatting operation or two updating some kind of metadata and wanting to stuff it in the `Fil` to not-redo.  Not seeing it in a quick look..

**Comment by c-blake** [comment]
Ah. The `[rwx]Ok` procs that `defPermOk` sets up which (in `--access` mode, e.g. if NFS/fancy ACLs make permission bits unreliable) need to be able to cache their answer and `fmtOperm` uses them.  That's why `var Fil`. :-)

**Comment by c-blake** [comment]
Also "classification" (which happens before formatting in sorting) also uses those `[rwx]Ok`.  By the time formatting happens, if access(2) calls did need to happen it would be the final time.  But then we would need two sets of `rOk` procs - one taking a non-var `Fil` and one a `var Fil`.  It seemed to me at the time that just doing `var Fil` was simplest.

**Comment by c-blake** [comment]
Anyway, this draft is looking pretty good.  That little `len` instead of `printedLen` optimization for `cf.plain` mode will probably break tabular shape with utf8 filenames...We could just do `runeLen` instead of `len` if you want that.

Let me know when you've tested it more on your VTE and are ready to merge.  I'd suggest at least `lc /var/log/*` and regular `lc` to test various abs./relative paths. I'm sure you can also come up with other things.  I don't really have any automated testing.  I just use it 100s of times per day, but in fewer than max modes.

**Comment by SolitudeSF** [comment]
do we support windows?

**Comment by c-blake** [comment]
No. There's tons o Unix only stuff.

**Comment by SolitudeSF** [comment]
phew, less work for me.

**Comment by SolitudeSF** [comment]
when running `lc /`, cf.pfx becomes `"//"`, is there a reason?

**Comment by SolitudeSF** [comment]
i think i implemented everything required by protocol.

**Comment by c-blake** [comment]
There is probably no exact reason. `qualPath` is used in a lot of places.  Might need to be careful it doesn't end up being empty string by accident.

**Comment by c-blake** [comment]
Have you tested that your VTE decodes your encoding correctly enough to want me to just merge this?  I see that you dropped Draft status.

**Comment by SolitudeSF** [comment]
think so, tested it on bunch of conditions/unicode stuff.
also, im not using VTE, but i tested it in VTE terminal too.

**Comment by c-blake** [comment]
Ok.  Well, I'll merge it and give it a few weeks of both of us testing it out live (me more in non-hyperlink mode...) before punching a release.

**Comment by c-blake** [comment]
This change is breaking `stat` metadata for me big time.  I haven't tracked down why.  More a tomorrow morning thing for me, but San Fran is on much earlier time and I got to be early.  So, maybe you'll get a chance to take a look.

**Comment by SolitudeSF** [comment]
potential fix in #3

**Pull request merged**
